const Types = {
  TEST: 'TEST',
  SAVEDEBUG: 'SAVEDEBUG',
  SAVE_USER_TOKEN: 'SAVE_USER_TOKEN',
  SAVE_USER: 'SAVE_USER',
  SET_APP_OPEN: 'SET_APP_OPEN',
  NETWORK_STATUS: 'NETWORK_STATUS',
  SHOW_LOADING: 'SHOW_LOADING',
  SET_LOADING: 'SET_LOADING',
  RECENT_SEARCH: 'RECENT_SEARCH',
  SET_OVERVIEW: 'SET_OVERVIEW',
  SAVE_COURSE: 'SAVE_COURSE',
  SAVE_WISHLIST: 'SAVE_WISHLIST',
};

export default Types;
