require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'Eduma' do
  config = use_native_modules!
  
  use_react_native!(:path => config["reactNativePath"],
  # to enable hermes on iOS, change `false` to `true` and then install pods
  :hermes_enabled => false
  
  )
  inhibit_all_warnings!

  # pod 'GoogleTagManager', '7.2.0', :configuration => 'Release'
  # pod 'GoogleAnalytics', :configuration => 'Release'
  # pod 'GoogleUtilitiesLegacy', :configuration => 'Release'
  # pod 'GoogleSymbolUtilities', :configuration => 'Release'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons' 

  target 'EdumaTests' do
    inherit! :complete
    # Pods for testing
  end

  # use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 11.0
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
        end
        config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
        config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
        config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
        if target.name == 'React-jsi'
          puts '*** Patching React-jsi pod...'
          puts '***'
          puts '*** - Adding NDEBUG=1 to silence the \'JSCRuntime destroyed with a dangling API object\''
          puts '***   crash upon reload.'
          puts '***'
          puts '*** This is caused by realm-js being loaded at runtime, when CodePush tries to'
          puts '*** reload the app. It\'s recommended to remove realm-js. After which this'
          puts '*** workaround can be removed from Podfile.'
          puts '***'
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'NDEBUG=1'
          puts '*** Done'
          puts '***'
        end
      end
    end
  end
end