import { StyleSheet, Dimensions, Platform } from 'react-native';
import { getStatusBarHeight } from 'app-common';

const deviceWidth = Dimensions.get('window').width;
const deviceHeight = Dimensions.get('window').height;

export default StyleSheet.create({
  container: {
    backgroundColor: '#fff',
    flex: 1,
    zIndex: 1,
    paddingTop: Platform.OS === 'ios' ? 0 : getStatusBarHeight(),
  },
  header: {
    paddingTop: Platform.OS === 'ios' ? getStatusBarHeight() : 0,
    marginTop: 20,
    paddingHorizontal: 16,
  },
  header1: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  inputSearch: {
    flex: 1,
    marginRight: 8,
    fontFamily: 'Poppins',
    fontSize: 14,
    lineHeight: 21,
    color: '#000',
  },
  iconBack: {
    height: 14,
    width: 14,
    resizeMode: 'contain',
    tintColor: '#000',
  },
  imgBanner: {
    width: (276 / 375) * deviceWidth,
    height: (209 / 375) * deviceWidth,
    resizeMode: 'contain',
    position: 'absolute',
    right: 0,
    top: 0,
    zIndex: -1,
  },
  title: {
    fontFamily: 'Poppins-Medium',
    fontWeight: '500',
    fontSize: 24,
    lineHeight: 36,
  },
  txt1: {
    fontFamily: 'Poppins-Medium',
    fontSize: 14,
    lineHeight: 21,
    color: '#C4C4C4',
    fontWeight: '500',
  },
  txt2: {
    fontFamily: 'Poppins-Medium',
    fontSize: 16,
    lineHeight: 24,
    color: '#fff',
    fontWeight: '500',
  },
  viewUpdateRole: {
    zIndex: 1000,
    flex: 1,
    position: 'absolute',
    // backgroundColor: 'rgba(0,0,0,0.5)',
    width: deviceWidth,
    height: deviceHeight,
  },
  viewModalFilter: {
    width: 127,
    height: 131,
    paddingHorizontal: 18,
    paddingVertical: 16,
    borderRadius: 6,
    backgroundColor: '#fff',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 10,
  },
  txtFilterItem: {
    marginBottom: 10,
    fontFamily: 'Poppins',
    fontSize: 10,
    lineHeight: 15,
    color: '#A9A9A9',
  },
  txtSearch: {
    fontFamily: 'Poppins',
    fontSize: 12,
    lineHeight: 18,
    color: '#939393',
  },
  txtItemFilter: {
    fontFamily: 'Poppins',
    fontSize: 12,
    lineHeight: 18,
    color: '#858585',
  },
  content: {
    marginTop: 23,
  },
  imageBanner: {
    width: deviceWidth,
    height: (250 / 375) * deviceWidth,
  },
  content2: {
    padding: 16,
  },
  icon: {
    width: 21,
    height: 21,
    resizeMode: 'contain',
    tintColor: '#FBC815',
  },
  icon1: {
    width: 16,
    height: 16,
    resizeMode: 'contain',
    tintColor: '#FBC815',
    marginLeft: 15,
  },
  txt3: {
    fontFamily: 'Poppins',
    fontSize: 12,
    lineHeight: 18,
    color: '#939393',
    marginLeft: 4,
  },
  price: {
    fontFamily: 'Poppins-Medium',
    fontSize: 16,
    lineHeight: 24,
    color: '#000',
    fontWeight: '500',
  },
  oldPrice: {
    fontFamily: 'Poppins',
    fontSize: 12,
    lineHeight: 18,
    color: '#B0B0B0',
    textDecorationLine: 'line-through',
    marginLeft: 13,
  },
  txtTitle: {
    fontFamily: 'Poppins-Medium',
    fontSize: 18,
    lineHeight: 27,
    color: '#000',
    fontWeight: '500',
    marginTop: 17,
  },
  subSectionTitle: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  txtSubSection: {
    fontFamily: 'Poppins-Medium',
    fontSize: 16,
    lineHeight: 22,
    color: '#000',
    fontWeight: '500',
    marginLeft: 10,
    justifyContent: 'flex-start',
    flex: 1,
  },
  txtLength: {
    fontFamily: 'Poppins-Medium',
    fontSize: 16,
    lineHeight: 22,
    color: '#000',
    fontWeight: '500',
    marginLeft: 10,
  },
  txtSubTitle: {
    fontFamily: 'Poppins-Medium',
    fontSize: 16,
    lineHeight: 22,
    color: '#000',
    fontWeight: '500',
    marginLeft: 10,
  },
  txtOverview: {
    marginTop: 13,
    fontFamily: 'Poppins-ExtraLight',
    fontSize: 13,
    lineHeight: 20,
    color: '#000',
    fontWeight: '300',
  },
  subTitle: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  totalHours: {
    fontFamily: 'Poppins-ExtraLight',
    fontSize: 10,
    color: '#8F8F8F',
    fontWeight: '300',
    marginLeft: 10,
  },
  txtItemLession: {
    flex: 1,
    fontFamily: 'Poppins-ExtraLight',
    fontSize: 12,
    lineHeight: 20,
    color: '#4E4E4E',
    fontWeight: '300',
    marginLeft: 10,
  },
  line: {
    width: deviceWidth - 32,
    marginBottom: 14,
    marginTop: 9,
    backgroundColor: '#F0F0F0',
    height: 1,
    alignSelf: 'center',
    flex: 1,
  },
  viewInstructor: {
    alignSelf: 'center',
    marginTop: 24,
    justifyContent: 'center',
    alignItems: 'center',
  },
  imgAvatar: {
    width: 51,
    height: 51,
    borderRadius: 51 / 2,
  },
  iconIns: {
    width: 14,
    height: 14,
    resizeMode: 'contain',
    tintColor: '#D2D2D2',
    marginHorizontal: 6,
  },
  txtBio: {
    fontFamily: 'Poppins-ExtraLight',
    fontSize: 13,
    lineHeight: 18,
    color: '#4E4E4E',
    fontWeight: '300',
    marginTop: 15,
    textAlign: 'center',
  },
  viewReview: {
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
  },
  txtRating: {
    fontFamily: 'Poppins-Medium',
    fontSize: 36,
    lineHeight: 54,
    color: '#FBC815',
    fontWeight: '500',
    textAlign: 'center',
  },
  txtNameRating: {
    flex: 1,
    fontFamily: 'Poppins',
    fontSize: 13,
    lineHeight: 16,
    color: '#777',
    marginTop: 0,
  },
  titleRating: {
    fontFamily: 'Poppins-Medium',
    fontSize: 13,
    lineHeight: 20,
    color: '#000000',
    fontWeight: '500',
  },
  bottom: {
    position: 'absolute',
    bottom: 0,
    paddingBottom: 30,
    paddingTop: 10,
    paddingHorizontal: 20,
    flexDirection: 'row',
    backgroundColor: '#f7f7f7',
    alignItems: 'center',
    borderTopWidth: 1,
    borderTopColor: '#f7f7f7',
  },
  btnBuy: {
    backgroundColor: '#FBC815',
    marginRight: 10,
    flex: 1,
    paddingVertical: 16,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    fontFamily: 'Poppins',
  },
  txtBuy: {
    fontFamily: 'Poppins-Medium',
    fontSize: 14,
    lineHeight: 21,
    color: '#000000',
    fontWeight: '500',
    flex: 1,
  },
  btnAddToCart: {
    backgroundColor: '#000000',
    marginLeft: 10,
    flex: 1,
    paddingVertical: 16,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    flexDirection: 'row',
  },
  txtAddToCart: {
    fontFamily: 'Poppins-Medium',
    fontSize: 14,
    lineHeight: 21,
    color: '#FFFFFF',
    fontWeight: '500',
  },
  iconCart: {
    width: 18,
    height: 18,
    marginRight: 8,
  },
  iconPreview: {
    fontSize: 16,
    color: '#25C717',
    marginLeft: 5,
  },
  txtTotal: {
    flex: 1,
    fontFamily: 'Poppins',
    fontSize: 14,
    lineHeight: 21,
    color: '#000',
  },
});
